// server/catalogData.js - Comprehensive product catalog with verified high-resolution images & e-commerce metadata

export const PRODUCT_CATALOG = [
  // ==========================================
  // PRODUCE (Fresh Fruits & Vegetables)
  // ==========================================
  {
    id: "prod_apple_gala",
    name: "Organic Gala Apples",
    category: "Produce",
    price: 3.99,
    originalPrice: 4.69,
    brand: "NatureFresh Farms",
    unit: "1 lb bag (approx 4 apples)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Autumn / Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["Organic", "Gluten-Free", "Vegan"],
    rating: 4.8,
    reviewsCount: 342,
    substitutes: ["prod_apple_honeycrisp", "prod_banana"],
    consumptionCycleDays: 7,
    emoji: "🍎",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80",
    description: "Sweet, crisp organic Gala apples hand-picked at peak orchard freshness."
  },
  {
    id: "prod_apple_honeycrisp",
    name: "Honeycrisp Apples",
    category: "Produce",
    price: 4.99,
    originalPrice: 5.49,
    brand: "Orchard Select",
    unit: "1 lb bag",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Autumn",
    isSale: false,
    dietary: ["Organic", "Gluten-Free", "Vegan"],
    rating: 4.9,
    reviewsCount: 189,
    substitutes: ["prod_apple_gala"],
    consumptionCycleDays: 7,
    emoji: "🍏",
    image: "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&w=400&q=80",
    description: "Premium juicy and extra crunchy Honeycrisp apples with balanced tartness."
  },
  {
    id: "prod_banana",
    name: "Fair-Trade Organic Bananas",
    category: "Produce",
    price: 1.89,
    originalPrice: 2.19,
    brand: "EquiFruit",
    unit: "1 bunch (approx 5-6 bananas)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Organic", "Vegan", "Potassium-Rich"],
    rating: 4.7,
    reviewsCount: 812,
    substitutes: [],
    consumptionCycleDays: 5,
    emoji: "🍌",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Creamy, naturally sweet bananas rich in potassium and Vitamin B6."
  },
  {
    id: "prod_spinach",
    name: "Baby Spinach Leaves",
    category: "Produce",
    price: 2.99,
    originalPrice: 3.75,
    brand: "Earthbound Farm",
    unit: "5 oz clamshell container",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Spring / Summer",
    isSale: true,
    discountPercent: 20,
    dietary: ["Organic", "Vegan", "Iron-Rich"],
    rating: 4.6,
    reviewsCount: 220,
    substitutes: [],
    consumptionCycleDays: 6,
    emoji: "🥬",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=400&q=80",
    description: "Tender, pre-washed baby spinach leaves perfect for salads, sautés, and smoothies."
  },
  {
    id: "prod_avocado",
    name: "Hass Avocados (3-Pack)",
    category: "Produce",
    price: 4.49,
    originalPrice: 4.99,
    brand: "SunGrove",
    unit: "3 ct mesh bag",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Spring / Summer",
    isSale: false,
    dietary: ["Organic", "Vegan", "Keto", "Healthy-Fats"],
    rating: 4.8,
    reviewsCount: 450,
    substitutes: [],
    consumptionCycleDays: 6,
    emoji: "🥑",
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=400&q=80",
    description: "Rich and buttery ready-to-eat Hass avocados packed with wholesome healthy fats."
  },
  {
    id: "prod_berries_straw",
    name: "Organic Fresh Strawberries",
    category: "Produce",
    price: 3.99,
    originalPrice: 4.49,
    brand: "Driscoll's",
    unit: "1 lb clamshell",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Summer",
    isSale: false,
    dietary: ["Organic", "Vegan", "Vitamin-C"],
    rating: 4.8,
    reviewsCount: 620,
    substitutes: ["prod_berries_blue"],
    consumptionCycleDays: 4,
    emoji: "🍓",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=400&q=80",
    description: "Luscious and aromatic sweet strawberries bursting with natural antioxidant flavor."
  },
  {
    id: "prod_berries_blue",
    name: "Fresh Blueberries",
    category: "Produce",
    price: 3.49,
    originalPrice: 3.99,
    brand: "Driscoll's",
    unit: "6 oz pack",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Summer",
    isSale: true,
    discountPercent: 12,
    dietary: ["Organic", "Antioxidant-Rich", "Vegan"],
    rating: 4.7,
    reviewsCount: 310,
    substitutes: ["prod_berries_straw"],
    consumptionCycleDays: 5,
    emoji: "🫐",
    image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?auto=format&fit=crop&w=400&q=80",
    description: "Plump, antioxidant-loaded sweet blueberries hand-picked in prime harvest season."
  },
  {
    id: "prod_tomatoes_roma",
    name: "Vine-Ripened Roma Tomatoes",
    category: "Produce",
    price: 2.29,
    originalPrice: 2.79,
    brand: "Campari Select",
    unit: "1 lb pack (approx 4-5 ct)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Organic", "Vegan", "Lycopene-Rich"],
    rating: 4.7,
    reviewsCount: 290,
    substitutes: [],
    consumptionCycleDays: 6,
    emoji: "🍅",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80",
    description: "Firm, rich and savory Roma plum tomatoes ideal for fresh sauces and salads."
  },
  {
    id: "prod_lemon_meyer",
    name: "Fresh Meyer Lemons",
    category: "Produce",
    price: 2.49,
    originalPrice: 2.99,
    brand: "Sunkist Organic",
    unit: "1 lb bag (approx 4 lemons)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["Organic", "Vegan", "Vitamin-C"],
    rating: 4.8,
    reviewsCount: 360,
    substitutes: [],
    consumptionCycleDays: 10,
    emoji: "🍋",
    image: "https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&w=400&q=80",
    description: "Juicy, aromatic sweet Meyer lemons perfect for dressings, cooking, and teas."
  },

  // ==========================================
  // DAIRY & EGGS
  // ==========================================
  {
    id: "dairy_milk_whole",
    name: "Whole Grade A Milk",
    category: "Dairy & Eggs",
    price: 3.89,
    originalPrice: 4.29,
    brand: "Horizon Organic",
    unit: "1 Gallon (128 fl oz)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Organic", "Calcium-Rich", "Gluten-Free"],
    rating: 4.8,
    reviewsCount: 940,
    substitutes: ["dairy_milk_oat", "dairy_milk_almond"],
    consumptionCycleDays: 7,
    emoji: "🥛",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80",
    description: "Rich, creamy whole milk from pasture-raised, grass-fed organic dairy cows."
  },
  {
    id: "dairy_milk_oat",
    name: "Oat Barista Blend Milk",
    category: "Dairy & Eggs",
    price: 4.79,
    originalPrice: 5.49,
    brand: "Oatly",
    unit: "64 fl oz carton",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 12,
    dietary: ["Plant-Based", "Vegan", "Dairy-Free", "Nut-Free"],
    rating: 4.9,
    reviewsCount: 710,
    substitutes: ["dairy_milk_almond", "dairy_milk_whole"],
    consumptionCycleDays: 9,
    emoji: "🌾",
    image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=400&q=80",
    description: "Silky oat barista milk designed for micro-foaming lattes, cereal, and baking."
  },
  {
    id: "dairy_milk_almond",
    name: "Unsweetened Almond Milk",
    category: "Dairy & Eggs",
    price: 3.49,
    originalPrice: 3.99,
    brand: "Califia Farms",
    unit: "48 fl oz bottle",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Plant-Based", "Vegan", "Dairy-Free", "Low-Calorie", "Keto"],
    rating: 4.7,
    reviewsCount: 530,
    substitutes: ["dairy_milk_oat", "dairy_milk_whole"],
    consumptionCycleDays: 10,
    emoji: "🥛",
    image: "https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?auto=format&fit=crop&w=400&q=80",
    description: "Ultra-smooth California almond milk with gentle, naturally nutty flavor."
  },
  {
    id: "dairy_eggs_freerange",
    name: "Pasture-Raised Brown Eggs",
    category: "Dairy & Eggs",
    price: 4.99,
    originalPrice: 5.79,
    brand: "Vital Farms",
    unit: "1 Dozen (12 ct)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Non-GMO", "Pasture-Raised", "Keto", "High-Protein"],
    rating: 4.9,
    reviewsCount: 1120,
    substitutes: [],
    consumptionCycleDays: 10,
    emoji: "🥚",
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=400&q=80",
    description: "Certified humane pasture-raised eggs with vibrant deep amber yolks."
  },
  {
    id: "dairy_greek_yogurt",
    name: "Greek Yogurt (Plain 0% Fat)",
    category: "Dairy & Eggs",
    price: 5.29,
    originalPrice: 6.25,
    brand: "Fage Total",
    unit: "32 oz tub",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["High-Protein", "Probiotic", "Gluten-Free"],
    rating: 4.8,
    reviewsCount: 420,
    substitutes: [],
    consumptionCycleDays: 8,
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&q=80",
    description: "All-natural strained Greek yogurt packed with 18g clean protein per serving."
  },
  {
    id: "dairy_butter_salted",
    name: "Pure Irish Butter (Salted)",
    category: "Dairy & Eggs",
    price: 4.69,
    originalPrice: 5.19,
    brand: "Kerrygold",
    unit: "8 oz (2 sticks)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Grass-Fed", "Keto", "Non-GMO"],
    rating: 4.9,
    reviewsCount: 680,
    substitutes: ["pantry_olive_oil"],
    consumptionCycleDays: 18,
    emoji: "🧈",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=400&q=80",
    description: "Golden grass-fed Irish butter with silky spreadable texture and rich creaminess."
  },
  {
    id: "dairy_cheese_cheddar",
    name: "Aged White Cheddar Block",
    category: "Dairy & Eggs",
    price: 4.49,
    originalPrice: 5.29,
    brand: "Cabot Vermont",
    unit: "8 oz block",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["Gluten-Free", "Keto", "High-Protein"],
    rating: 4.9,
    reviewsCount: 510,
    substitutes: [],
    consumptionCycleDays: 14,
    emoji: "🧀",
    image: "https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=400&q=80",
    description: "Sharp, naturally aged Vermont cheddar with a bold, complex savory finish."
  },

  // ==========================================
  // BAKERY & BREADS
  // ==========================================
  {
    id: "bakery_sourdough",
    name: "Artisan Sourdough Boule",
    category: "Bakery",
    price: 4.99,
    originalPrice: 5.69,
    brand: "Boulangerie Moderne",
    unit: "24 oz loaf",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Vegan", "Naturally-Fermented", "Non-GMO"],
    rating: 4.8,
    reviewsCount: 540,
    substitutes: ["bakery_bagels_everything"],
    consumptionCycleDays: 5,
    emoji: "🍞",
    image: "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=400&q=80",
    description: "Slow-fermented wild sourdough with blistered golden crust and chewy airy crumb."
  },
  {
    id: "bakery_croissant",
    name: "French All-Butter Croissants (4-Pack)",
    category: "Bakery",
    price: 4.79,
    originalPrice: 5.49,
    brand: "St. Michel",
    unit: "4 ct pack",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: true,
    season: "Weekend Special",
    isSale: false,
    dietary: ["Vegetarian"],
    rating: 4.8,
    reviewsCount: 390,
    substitutes: [],
    consumptionCycleDays: 4,
    emoji: "🥐",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=400&q=80",
    description: "Flaky, buttery Parisian style breakfast croissants baked with French Normandy butter."
  },
  {
    id: "bakery_bagels_everything",
    name: "New York Everything Bagels (5-Pack)",
    category: "Bakery",
    price: 3.99,
    originalPrice: 4.69,
    brand: "Thomas'",
    unit: "5 ct bag (20 oz)",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["Vegan", "Kosher"],
    rating: 4.6,
    reviewsCount: 280,
    substitutes: ["bakery_sourdough"],
    consumptionCycleDays: 6,
    emoji: "🥯",
    image: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=400&q=80",
    description: "Boiled and baked bagels generously crusted with garlic, onion, poppy, and sesame."
  },

  // ==========================================
  // PANTRY & GRAINS
  // ==========================================
  {
    id: "pantry_olive_oil",
    name: "Extra Virgin Olive Oil (Cold-Pressed)",
    category: "Pantry",
    price: 11.99,
    originalPrice: 13.99,
    brand: "California Olive Ranch",
    unit: "750 mL bottle",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Organic", "Keto", "Heart-Healthy", "Vegan"],
    rating: 4.9,
    reviewsCount: 880,
    substitutes: [],
    consumptionCycleDays: 30,
    emoji: "🫒",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80",
    description: "First cold-pressed 100% California extra virgin olive oil with fruity floral notes."
  },
  {
    id: "pantry_pasta_organic",
    name: "Bronze-Cut Spaghetti Pasta",
    category: "Pantry",
    price: 2.49,
    originalPrice: 2.99,
    brand: "De Cecco",
    unit: "1 lb box (16 oz)",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Non-GMO", "Vegan"],
    rating: 4.8,
    reviewsCount: 460,
    substitutes: [],
    consumptionCycleDays: 14,
    emoji: "🍝",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80",
    description: "Traditional slow-dried Italian pasta made with 100% durum semolina wheat."
  },
  {
    id: "pantry_honey_raw",
    name: "Raw Organic Wildflower Honey",
    category: "Pantry",
    price: 7.99,
    originalPrice: 8.99,
    brand: "Nature Nate's",
    unit: "16 oz squeeze bottle",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["100% Pure Raw", "Unfiltered", "Gluten-Free"],
    rating: 4.8,
    reviewsCount: 510,
    substitutes: [],
    consumptionCycleDays: 35,
    emoji: "🍯",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=400&q=80",
    description: "Unheated, unfiltered raw honey rich in natural floral enzymes and pollen."
  },
  {
    id: "pantry_rice_basmati",
    name: "Royal Himalayan Basmati Rice",
    category: "Pantry",
    price: 5.99,
    originalPrice: 6.99,
    brand: "Royal",
    unit: "5 lb burlap bag",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 14,
    dietary: ["Gluten-Free", "Non-GMO", "Vegan"],
    rating: 4.9,
    reviewsCount: 630,
    substitutes: [],
    consumptionCycleDays: 25,
    emoji: "🍚",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Aged long-grain authentic Himalayan basmati with signature nutty aroma."
  },
  {
    id: "pantry_oats_rolled",
    name: "Organic Whole Grain Rolled Oats",
    category: "Pantry",
    price: 3.79,
    originalPrice: 4.29,
    brand: "Bob's Red Mill",
    unit: "32 oz bag",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Whole Grain", "High-Fiber", "Heart-Healthy", "Vegan"],
    rating: 4.8,
    reviewsCount: 480,
    substitutes: [],
    consumptionCycleDays: 20,
    emoji: "🥣",
    image: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=400&q=80",
    description: "Kiln-toasted old fashioned rolled oats for wholesome morning oatmeal and baking."
  },

  // ==========================================
  // MEAT & SEAFOOD
  // ==========================================
  {
    id: "meat_chicken_breast",
    name: "Organic Boneless Chicken Breasts",
    category: "Meat & Seafood",
    price: 8.99,
    originalPrice: 10.49,
    brand: "Bell & Evans",
    unit: "1.25 lb pack (~3 fillets)",
    inStock: true,
    deliveryTime: "12 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Organic", "Antibiotic-Free", "Keto", "High-Protein"],
    rating: 4.8,
    reviewsCount: 730,
    substitutes: ["meat_tofu_firm"],
    consumptionCycleDays: 6,
    emoji: "🍗",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400&q=80",
    description: "Air-chilled organic chicken breasts raised without hormones or antibiotics."
  },
  {
    id: "meat_salmon_wild",
    name: "Wild Alaskan Sockeye Salmon Fillet",
    category: "Meat & Seafood",
    price: 12.99,
    originalPrice: 15.29,
    brand: "Wild Planet",
    unit: "1 lb fillet portion",
    inStock: true,
    deliveryTime: "12 MINS",
    isSeasonal: true,
    season: "Summer / Autumn",
    isSale: true,
    discountPercent: 15,
    dietary: ["Wild-Caught", "Omega-3 Rich", "Keto", "Gluten-Free"],
    rating: 4.9,
    reviewsCount: 420,
    substitutes: ["meat_chicken_breast"],
    consumptionCycleDays: 5,
    emoji: "🐟",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80",
    description: "Sustainably harvested vibrant red salmon fillet brimming with heart-healthy omega-3s."
  },
  {
    id: "meat_tofu_firm",
    name: "Organic Extra Firm Tofu",
    category: "Meat & Seafood",
    price: 2.49,
    originalPrice: 3.10,
    brand: "House Foods",
    unit: "14 oz block",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 20,
    dietary: ["Certified Vegan", "Organic", "Gluten-Free", "Low-Calorie"],
    rating: 4.7,
    reviewsCount: 310,
    substitutes: ["meat_chicken_breast"],
    consumptionCycleDays: 8,
    emoji: "🌱",
    image: "https://images.unsplash.com/photo-1584278860047-22db9ff82bed?auto=format&fit=crop&w=400&q=80",
    description: "Dense non-GMO organic soybean tofu that sears and absorbs marinades beautifully."
  },

  // ==========================================
  // BEVERAGES
  // ==========================================
  {
    id: "bev_coffee_coldbrew",
    name: "Cold Brew Coffee Concentrate",
    category: "Beverages",
    price: 6.49,
    originalPrice: 7.29,
    brand: "Chameleon Cold Brew",
    unit: "32 fl oz bottle",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: true,
    season: "Spring / Summer",
    isSale: true,
    discountPercent: 10,
    dietary: ["Organic", "Zero-Sugar", "Keto", "Vegan"],
    rating: 4.8,
    reviewsCount: 650,
    substitutes: ["bev_tea_green"],
    consumptionCycleDays: 10,
    emoji: "☕",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=400&q=80",
    description: "16-hour slow-steeped Arabica coffee concentrate with ultra-smooth chocolate notes."
  },
  {
    id: "bev_sparkling_water",
    name: "Lime Sparkling Water (8-Pack)",
    category: "Beverages",
    price: 4.99,
    originalPrice: 5.49,
    brand: "Spindrift",
    unit: "8 x 12 fl oz cans",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Real Squeezed Fruit", "Zero Added Sugar", "Gluten-Free", "Vegan"],
    rating: 4.9,
    reviewsCount: 890,
    substitutes: [],
    consumptionCycleDays: 7,
    emoji: "🫧",
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80",
    description: "Crisp sparkling canned water with real squeezed California lime juice."
  },
  {
    id: "bev_tea_green",
    name: "Organic Ceremonial Matcha Green Tea",
    category: "Beverages",
    price: 8.49,
    originalPrice: 9.99,
    brand: "Ippodo Tea",
    unit: "1.5 oz tin (30g)",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["Organic", "Antioxidant-Rich", "Keto", "Vegan"],
    rating: 4.9,
    reviewsCount: 410,
    substitutes: ["bev_coffee_coldbrew"],
    consumptionCycleDays: 20,
    emoji: "🍵",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80",
    description: "First-harvest ceremonial grade Uji matcha with vibrant green color and umami sweetness."
  },

  // ==========================================
  // SNACKS & SWEETS
  // ==========================================
  {
    id: "snack_dark_chocolate",
    name: "85% Cocoa Sea Salt Dark Chocolate",
    category: "Snacks",
    price: 3.49,
    originalPrice: 3.99,
    brand: "Hu Kitchen",
    unit: "2.1 oz bar",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Organic", "Paleo", "Vegan", "No Refined Sugar"],
    rating: 4.9,
    reviewsCount: 520,
    substitutes: ["snack_almonds_roasted"],
    consumptionCycleDays: 8,
    emoji: "🍫",
    image: "https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&w=400&q=80",
    description: "Micro-batch dark chocolate sweetened with organic coconut sugar and hand-harvested sea salt."
  },
  {
    id: "snack_almonds_roasted",
    name: "Smoked Sea Salt Roasted Almonds",
    category: "Snacks",
    price: 5.99,
    originalPrice: 6.99,
    brand: "Blue Diamond",
    unit: "10 oz bag",
    inStock: true,
    deliveryTime: "8 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: true,
    discountPercent: 15,
    dietary: ["Keto", "High-Protein", "Gluten-Free", "Vegan"],
    rating: 4.8,
    reviewsCount: 470,
    substitutes: ["snack_dark_chocolate"],
    consumptionCycleDays: 14,
    emoji: "🥜",
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=400&q=80",
    description: "Crunchy oven-roasted California almonds kissed with aromatic natural hickory smoke."
  },

  // ==========================================
  // HOUSEHOLD & CLEANING
  // ==========================================
  {
    id: "house_dish_soap",
    name: "Plant-Based Dish Soap (Clementine)",
    category: "Household",
    price: 3.99,
    originalPrice: 4.49,
    brand: "Method",
    unit: "18 fl oz pump bottle",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Eco-Friendly", "Cruelty-Free", "Biodegradable"],
    rating: 4.8,
    reviewsCount: 390,
    substitutes: [],
    consumptionCycleDays: 30,
    emoji: "🧼",
    image: "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=400&q=80",
    description: "Tough on grease, gentle on hands with fresh zesty citrus essential oils."
  },
  {
    id: "house_toothpaste",
    name: "Natural Whitening Toothpaste",
    category: "Household",
    price: 4.79,
    originalPrice: 5.29,
    brand: "Tom's of Maine",
    unit: "4.7 oz tube",
    inStock: true,
    deliveryTime: "10 MINS",
    isSeasonal: false,
    season: "Year-round",
    isSale: false,
    dietary: ["Fluoride-Free", "Cruelty-Free"],
    rating: 4.6,
    reviewsCount: 290,
    substitutes: [],
    consumptionCycleDays: 45,
    emoji: "🪥",
    image: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=400&q=80",
    description: "Naturally sourced fluoride-free whitening toothpaste flavored with real wild peppermint."
  }
];

export const CATEGORIES = [
  "All",
  "Produce",
  "Dairy & Eggs",
  "Bakery",
  "Pantry",
  "Meat & Seafood",
  "Beverages",
  "Snacks",
  "Household"
];

export const USER_PURCHASE_HISTORY = [
  { productId: "dairy_milk_whole", lastPurchasedDaysAgo: 8, frequencyDays: 7, totalBought: 12 },
  { productId: "bakery_sourdough", lastPurchasedDaysAgo: 6, frequencyDays: 5, totalBought: 9 },
  { productId: "dairy_eggs_freerange", lastPurchasedDaysAgo: 11, frequencyDays: 10, totalBought: 14 },
  { productId: "prod_banana", lastPurchasedDaysAgo: 6, frequencyDays: 5, totalBought: 16 },
  { productId: "pantry_olive_oil", lastPurchasedDaysAgo: 32, frequencyDays: 30, totalBought: 3 },
  { productId: "bev_coffee_coldbrew", lastPurchasedDaysAgo: 12, frequencyDays: 10, totalBought: 8 },
  { productId: "house_dish_soap", lastPurchasedDaysAgo: 35, frequencyDays: 30, totalBought: 4 }
];
